// AUTO-GENERATED — do not edit by hand.
// Regenerated by .github/workflows/parallax-manifest.yml whenever files in
// images/parallax/ change, so the archive views pick up new images automatically.
window.PARALLAX_IMAGES = [
  "V2.2.png",
  "p01.png",
  "p02.png",
  "p03.png",
  "p04.png",
  "p05.png",
  "p06.png",
  "p07.png",
  "p22.png",
  "p23.png",
  "p24.png",
  "p25.png",
  "p26.png",
  "p27.png",
  "p28.png",
  "p29.png",
  "p30.png",
  "p31.png",
  "p32.png",
  "p33.png",
  "p34.png",
  "p35.png",
  "p36.png",
  "p37.png",
  "p38.png",
  "p39.png",
  "p40.png"
];
